<a href="https://colab.research.google.com/github/shivamsingh163248/Coding-Ninjas-Solutions/blob/main/Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#now lerning the arrays indexing
import numpy as np
arr = np.array([3,4,5,6,67,7,8,9])
print(arr[1])

4


In [ ]:
import numpy as np
arr = np.array([5,6,7,8,92,3,3])
print(arr[1])

6


In [ ]:
import numpy as np
arr = np.array([5,6,7,8,92,3,3])
print(arr[1] + arr[2])

13


In [ ]:
#creating the 2d arrays
import numpy as np
arr = np.array([[1,2,3,4] , [5,6,7,8]])
print(arr.ndim)
print(arr[1,1])

2
6


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5,6,7,8],[3,4,5,6,7,8,9,0]])
print(arr.ndim)
#access the element
print("this is the element " , arr[1,2])

2
this is the element  5


In [ ]:
#creating the 3d arrasys
import numpy as np
arr = np.array([[[2,3,4] , [4,5,6]] , [[2,3,4] , [4,5,6]] , [[2,3,4] , [4,5,6]]])

#check the dimesion of the arrays
print(arr.ndim)
print(arr[0, 1, 2])

3
6


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])



Last element from 2nd dim:  10


In [ ]:
#creating the slince of the rrasy [start:end : step]
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::-1])

[7 6 5 4 3 2 1]


In [ ]:
import numpy as np
arr = np.array([[3,4,5,4] , [4,6,7,6]])
print(arr[1,0:2])

[4 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])
print(arr[::-2])

[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
[7 5 3 1]


In [ ]:
#now learning the slice values
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 0::2])

[ 6  8 10]


In [ ]:
#return the

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
#creating the 2d dimesion arraays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2 , 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)
print(type(arr))

int64
<class 'numpy.ndarray'>


In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
print(int(4.5))

4


In [ ]:
print(int(float("4.5")))

4
